### ISSUE TITLE
Agree on LightWallet gRPC Services to be Deprecated.

### ISSUE THREAD

**Issue by idky137** [zingolabs/zingo-proxy#70]
The current set of lightwallet gRPC services hold redundant functionality and, as we are currently re-implementing this service in rust, we would like to collect the set of gRPC services that zcash lightclients either currently use or plan to use in the future, with the hope that the current set can be simplified.

There is also a conversation going on regarding the serving of transparent tx data and whether this should be included in compact blocks rather than in a separate get_t_address_txids service. As this service can link client IP address to thier transparent address [#71].

The full list of lightwallet gRPC services currently offered is as follows:
    - rpc GetLatestBlock(ChainSpec) returns (BlockID)
    - rpc GetBlock(BlockID) returns (CompactBlock)
    - rpc GetBlockNullifiers(BlockID) returns (CompactBlock)
    - rpc GetBlockRange(BlockRange) returns (stream CompactBlock)
    - rpc GetBlockRangeNullifiers(BlockRange) returns (stream CompactBlock)
    - rpc GetTransaction(TxFilter) returns (RawTransaction)
    - rpc SendTransaction(RawTransaction) returns (SendResponse)
    - rpc GetTaddressTxids(TransparentAddressBlockFilter) returns (stream RawTransaction)
    - rpc GetTaddressBalance(AddressList) returns (Balance)
    - rpc GetTaddressBalanceStream(stream Address) returns (Balance)
    - rpc GetMempoolTx(Exclude) returns (stream CompactTx)
    - rpc GetMempoolStream(Empty) returns (stream RawTransaction)
    - rpc GetTreeState(BlockID) returns (TreeState)
    - rpc GetLatestTreeState(Empty) returns (TreeState)
    - rpc GetSubtreeRoots(GetSubtreeRootsArg) returns (stream SubtreeRoot)
    - rpc GetAddressUtxos(GetAddressUtxosArg) returns (GetAddressUtxosReplyList)
    - rpc GetAddressUtxosStream(GetAddressUtxosArg) returns (stream GetAddressUtxosReply)
    - rpc GetLightdInfo(Empty) returns (LightdInfo)
    - rpc Ping(Duration) returns (PingResponse)

- *NOTE: This issue is for discussing the functionality required by "light" wallets using lightwalletd / zaino's gRPC services, there is a separate set of issues [#69, #72] for discussing functionality required by "full node" / SDK wallets.

**Comment by idky137** [comment]
The services Zingolib currently use are:
- get_latest_block
- get_block_range
- get_transaction
- send_transaction
- get_taddress_txids
- get_mempool_stream
- get_tree_state
- get_lightd_info

**Comment by Oscar-Pepper** [comment]
zingo's new sync implementation will use `GetSubtreeRoots` also.

**Comment by idky137** [comment]
Current proposed deprecations and changes:

Deprecate:
- rpc GetTaddressBalanceStream(stream Address) returns (Balance)
- rpc GetAddressUtxos(GetAddressUtxosArg) returns (GetAddressUtxosReplyList)
- rpc GetAddressUtxosStream(GetAddressUtxosArg) returns (stream GetAddressUtxosReply)

*Update:
- rpc GetMempoolTx(Exclude) returns (stream CompactTx)
- rpc GetMempoolStream(Empty) returns (stream RawTransaction)
(Should these 2 RPC be merged into a single RPC (GetMempoolStream) that returns (stream CompactTx) as this RPC is only used by lightwallets? This would be more data efficient and would allow wallets to identify any transactions connected to the wallet.)

**Comment by idky137** [comment]
'rpc GetAddressUtxos(GetAddressUtxosArg) returns (GetAddressUtxosReplyList)' has been requested. 

If possible we would still like to deprecate 'rpc GetAddressUtxosStream(GetAddressUtxosArg) returns (stream GetAddressUtxosReply)'.

**Comment by idky137** [comment]
After consideration, the only lightwallet service we plan to deprecate is `GetTaddressBalanceStream (stream Address) returns (Balance)`. There is already `GetTaddressBalance (AddressList) returns (Balance)`  that serves the same functionality and if a streaming variant is required then we would prefer to return a stream than receive one.  We would like to avoid receiving request streams as this can become slow when running over mixnets and can be an easy source of server congestion.
